export const APPOINTMENTS = [
  {
    id: 1,
    doctorId: 1,
    date: '2025-04-14',
    time: '08:30',
    patient: 'Jan Nowak',
    reason: 'Ból w klatce piersiowej',
  },
  {
    id: 2,
    doctorId: 2,
    date: '2025-04-14',
    time: '10:00',
    patient: 'Anna Zielińska',
    reason: 'Bóle głowy',
  },
  {
    id: 3,
    doctorId: 1,
    date: '2025-04-14',
    time: '11:30',
    patient: 'Kacper Malinowski',
    reason: 'Kontrola kardiologiczna',
  },
  {
    id: 4,
    doctorId: 3,
    date: '2025-04-15',
    time: '09:00',
    patient: 'Karolina Kwiatkowska',
    reason: 'Ból kolana',
  },
  {
    id: 5,
    doctorId: 4,
    date: '2025-04-15',
    time: '13:00',
    patient: 'Mateusz Cichoń',
    reason: 'Przegląd dentystyczny',
  },
  {
    id: 6,
    doctorId: 5,
    date: '2025-04-16',
    time: '08:30',
    patient: 'Magdalena Mazur',
    reason: 'Konsultacja diabetologiczna',
  },
  {
    id: 7,
    doctorId: 1,
    date: '2025-04-16',
    time: '10:00',
    patient: 'Paweł Walczak',
    reason: 'Echo serca',
  },
  {
    id: 8,
    doctorId: 3,
    date: '2025-04-16',
    time: '12:30',
    patient: 'Iga Sobczak',
    reason: 'Zwichnięcie stawu',
  },
  {
    id: 9,
    doctorId: 2,
    date: '2025-04-16',
    time: '15:00',
    patient: 'Dominika Sadowska',
    reason: 'Zawroty głowy',
  },
  {
    id: 10,
    doctorId: 6,
    date: '2025-04-17',
    time: '09:00',
    patient: 'Tomasz Jabłoński',
    reason: 'Wysoka gorączka u dziecka',
  },
  {
    id: 11,
    doctorId: 4,
    date: '2025-04-17',
    time: '13:30',
    patient: 'Julia Piotrowska',
    reason: 'Leczenie kanałowe',
  },
  {
    id: 12,
    doctorId: 5,
    date: '2025-04-18',
    time: '08:30',
    patient: 'Michał Zawadzki',
    reason: 'Insulina – korekta dawki',
  },
  {
    id: 13,
    doctorId: 3,
    date: '2025-04-18',
    time: '10:00',
    patient: 'Łukasz Król',
    reason: 'Rehabilitacja po urazie',
  },
  {
    id: 14,
    doctorId: 6,
    date: '2025-04-18',
    time: '12:00',
    patient: 'Ola Krajewska',
    reason: 'Bilans dwulatka',
  },
  {
    id: 15,
    doctorId: 2,
    date: '2025-04-18',
    time: '14:00',
    patient: 'Tadeusz Duda',
    reason: 'Problemy z pamięcią',
  },
  {
    id: 16,
    doctorId: 1,
    date: '2025-04-18',
    time: '15:30',
    patient: 'Edyta Ławniczak',
    reason: 'EKG i konsultacja',
  },
  {
    id: 17,
    doctorId: 4,
    date: '2025-04-19',
    time: '09:00',
    patient: 'Wojciech Górka',
    reason: 'Wyrwanie ósemki',
  },
  {
    id: 18,
    doctorId: 6,
    date: '2025-04-19',
    time: '11:30',
    patient: 'Zofia Zielonka',
    reason: 'Szczepienie dziecka',
  },
  {
    id: 19,
    doctorId: 1,
    date: '2025-04-19',
    time: '13:30',
    patient: 'Maciej Orlik',
    reason: 'Kontrola serca',
  },
];
